COMP: Fix compilation errors with Oracle Studio 12.4 and GCC 4.x
      These compilers complained about "Logicals must be compared with
      .eqv. instead of .eq.". The nightly regression benchmark found
      this.

git-svn-id: https://svn.mathematik.tu-dortmund.de:20443/svn/Featflow2@12022 4f116ff2-4e46-254c-a92c-0a7323bc4f3a