COMP: Fixed compilation on Ubuntu 14.04.4 LTS
      The changes in this commit are mainly taken from those made in
      revision 11789 (but that got reverted later in revision 12212).
      Citing the commit message from revision 11789:

        "According to

          http://gcc.gnu.org/gcc-4.8/porting_to.html

         some default pre-includes have been introduced since GNU cpp
         4.8.2. This breaks the use of cpp as pre-processor for Fortran
         files. As a workaround, the stdc-predef.h preinclude can be
         disabled with the use of -ffreestanding."

      So, when detecting GCC 4.8.x or higher use the GNU C preprocessor
      always with the command line argument -ffreestanding to avoid the
      following syntax error while compiling:

         /path/to/object/directory/fsystem.f90:1.1:
          /* Copyright (C) 1991-2014 Free Software Foundation, Inc.
          1
          Error: Invalid character in name at (1)

      Also: note that the recommendation from
      http://gcc.gnu.org/gcc-4.8/porting_to.html to use the preprocessor
      flag -P for non C/C++ code should not be used since it removes all
      comment lines which makes debugging very difficult.

git-svn-id: https://svn.mathematik.tu-dortmund.de:20443/svn/Featflow2@12240 4f116ff2-4e46-254c-a92c-0a7323bc4f3a